/**
 * Regenerates DESIGN_SYSTEM.md from apps/docs/src/design-system/catalog.ts —
 * the same structured data that drives the live `/design-system` showcase
 * (prop tables, examples, do/don't guidelines). One source of truth: never
 * hand-edit DESIGN_SYSTEM.md, edit catalog.ts and re-run this (SS-102).
 *
 * Run: `npm run gen:component-docs` (from the repo root).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { CATEGORIES, COMPONENTS, SEMANTIC_TONES, type CategoryId } from '../apps/docs/src/design-system/catalog.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'DESIGN_SYSTEM.md');

function fence(code: string): string {
  return '```tsx\n' + code.trim() + '\n```';
}

// A raw `|` inside a table cell (e.g. a union type like 'a' | 'b') would
// otherwise be read as an extra column separator and break the table.
function cell(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function propsTable(props: { name: string; type: string; default?: string; description: string }[]): string {
  if (props.length === 0) return '_No documented props._';
  const rows = props.map((p) => `| \`${cell(p.name)}\` | \`${cell(p.type)}\` | ${p.default ? `\`${cell(p.default)}\`` : '—'} | ${cell(p.description)} |`);
  return ['| Prop | Type | Default | Description |', '| --- | --- | --- | --- |', ...rows].join('\n');
}

function componentSection(c: (typeof COMPONENTS)[number]): string {
  const lines: string[] = [];
  lines.push(`### ${c.name}`, '');
  lines.push(c.summary, '');
  lines.push('#### Props', '', propsTable(c.props), '');
  if (c.examples && c.examples.length > 0) {
    lines.push('#### Examples', '');
    for (const ex of c.examples) {
      lines.push(`**${ex.title}**${ex.description ? ` — ${ex.description}` : ''}`, '', fence(ex.code), '');
    }
  } else {
    lines.push('#### Usage', '', fence(c.code), '');
  }
  if (c.guidelines) {
    lines.push('#### Guidelines', '');
    if (c.guidelines.do.length > 0) lines.push('Do:', ...c.guidelines.do.map((d) => `- ${d}`), '');
    if (c.guidelines.dont.length > 0) lines.push("Don't:", ...c.guidelines.dont.map((d) => `- ${d}`), '');
  }
  return lines.join('\n');
}

function build(): string {
  const out: string[] = [];
  out.push(
    '<!-- Generated by scripts/generate-design-system-docs.ts from apps/docs/src/design-system/catalog.ts — do not hand-edit; re-run `npm run gen:component-docs` after changing catalog.ts. -->',
    '',
    '# Sereno Design System — component reference',
    '',
    'Sereno DS is a token-driven React component library (`@sereno-ds/ui` + `@sereno-ds/tokens`) for the' +
      ' Sereno scheduling/booking platform — inline styles reading CSS custom properties, no UI base' +
      ' library, native light/dark theming. This file is the detailed, per-component reference (SS-102):' +
      ' every prop, every documented example, every do/don’t. For the short orientation an agent reads' +
      ' before touching code — repo layout, unbreakable rules, versioning, board flow — see `AGENTS.md`' +
      ' (SS-103) instead. The live, interactive version of everything below is the `/design-system`' +
      ' showcase in `apps/docs` — same data, rendered with working demos.',
    '',
    '## Semantic tones',
    '',
    `Shared by \`Badge\`, \`Alert\` and \`Toast\` — the same five words everywhere: ${SEMANTIC_TONES.map((t) => `\`${t}\``).join(', ')}.`,
    '',
    '## Categories',
    '',
  );
  for (const cat of CATEGORIES) {
    const inCat = COMPONENTS.filter((c) => c.category === cat.id);
    out.push(`- **${cat.label}** — ${cat.blurb} (${inCat.map((c) => c.name).join(', ')})`);
  }
  out.push('');
  const byCategory = new Map<CategoryId, typeof COMPONENTS>();
  for (const cat of CATEGORIES) byCategory.set(cat.id, []);
  for (const c of COMPONENTS) byCategory.get(c.category)!.push(c);
  for (const cat of CATEGORIES) {
    const comps = byCategory.get(cat.id)!;
    if (comps.length === 0) continue;
    out.push(`## ${cat.label}`, '', cat.blurb, '');
    for (const c of comps) out.push(componentSection(c), '');
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

writeFileSync(OUT, build(), 'utf8');
console.log(`Wrote ${OUT} — ${COMPONENTS.length} components.`);
